### PR TITLE
Message from God: I Have removed ERP from LiquidClaw13!!!!!! ft. Based Lads.

### PR DESCRIPTION
**Pull request by SwiGs1**
bye bye erp, and bye bye erpers!!!

## Description

To quote the discord annoucement: 

> "We've decided, although the general consensus was that we implement erp into something that could be used for admemes, we feel at liquidclaw13 that due to erp's reputation on fallout 13 that it has no place and does not belong in the game at any level at this point in time. We want to start fresh and wipe the slate clean and hope that people will come to play fallout for fallout. If you wanna do that shit, there are other servers out there waiting for you with open arms. If you're one of those people, probably don't belong here. Its for the best, it attracts the wrong kind've crowd, and you gotta look is in the hall of fame to find that out. Maybe later down the line, unlikely as it may be, it might be added back for admemes, but dont expect it. As a final note to end off, it really does add nothing to the game. And is retarded, the present benefits may be that f13 is known for it and the erpers can spread word of mouth faster, but it'll never outweigh the future costs."

## Motivation and Context
As in the quote. It adds no substance or anything to the game beyond an disgusting erp fetish standpoint, at the end of the day, this is 2d spessman game adapted for fallout. As with every erpers, and my consensus on erp. Just go watch porn, or go on 4chan or something you creeps, it doesnt belong in a video game, the plus side is, no need for the 18+ rule anymore. It attracts the wrong kind of crowd that we dont really want on liquidclaw13, and there are plenty of servers for that silly stuff if you want it anyway. We hope that people come to play fallout, for fallout, sure these subjects and i guess erotic stuff exists in the lore, but its always been either suggestive or not explicity shown, and only ever talked about. It aint an excuse to add it in tbh, but at the same time it does make for really good admemes, so in the future, this could be implemented for admeme stuff, for shitters or funny maymay events, etc, probably very unlikely tho. But at the end of the day erp and erpers are not needed or wanted here at thats whats happening. 

## How Has This Been Tested?
by me, just now, did it works, all done

## Changelog (necessary)
:cl:
del: everything involving ERP and now they got JACK SHIT!!!
/:cl:

### CODE REVIEW

**Comment by waterwater1212** [comment]
and if anyone asks, we never had it.

**Comment by SwiGs1** [comment]
ITS GONE!!! TERMINATED HAS LA VISTA!!! but fr tho, its gone, removed all the rubbish and removed it from preferences, so there no toggling verbs, because in this timeline, verb dont exist... @waterwater1212

**Comment by SwiGs1** [comment]
https://tenor.com/view/terminated-the-apprentice-gif-9973985

**Comment by MCterra10** [comment]
Why did you just comment it out lmfao

**Comment by SwiGs1** [comment]
@MCterra10 

>  so in the future, this could be implemented for admeme stuff, for shitters or funny maymay events, etc, probably very unlikely tho
Specsavers???

**Comment by MCterra10** [comment]
This is censorship

**Comment by SwiGs1** [comment]
a falsehood. MCTerra.

**Pull request merged**
